trunk/source/Tools.cpp
Will properly format negative numbers (i.e. -10.600$ instead of -10.-600$), see http://discoverygc.com/forums/showthread.php?tid=134618
=> Show absolute representation of less significant digits

trunk/plugins/autobuy/Main.cpp
Handle negative iCount values properly (i.e. due to bot capacity nerf), see: http://discoverygc.com/forums/showthread.php?tid=134618 (it should have displayed -53 instead of 4294967243). This change will make AUTOBUY_CARTITEM->iCount consistent with CARGO_INFO->iCount.
NOTE: I don't have access to a test environment at the moment (I'm away for the holidays) so I haven't been able to test this change yet. It looks to me like it should be good, but if you have any doubts at all then don't merge it yet.
=> Change AUTOBUY_CARTITEM iCount to signed int

trunk/plugins/playercntl_plugin/Main.cpp
=> playercntl: Don't pretend reloadlockedships command is unknown after executing it

Plugins/Public/base_plugin/CoreModule.cpp, Plugins/Public/base_plugin/Main.cpp, Plugins/Public/base_plugin/Main.h
This change to the base plugin decouples the wear and tear tickrate from the general base tickrate. This will allow server admins to increase the time between wear and tear damage while not affecting the general tickrate of the base plugin.
This change adds the "damage_tick_time" configuration option to the base plugin's configuration file. It functions in the same manner as the "tick_time" configuration option, but for the wear and tear tickrate instead of the general tickrate.
=> base_plugin: Add damage_tick_time config value for wear and tear tickrate

Plugins/Public/playercntl_plugin/Main.cpp, Plugins/Public/playercntl_plugin/MiscCmds.cpp
There was a post on discoverygc saying that they'd like more dice features. 
Dice command rewritten to support 1d20[+-] operations.
Image attached for ingame visual
The line explaining what each individual dice roll was is not displayed if there are more than 9 dice being rolled. Keep the screen clean from too much clutter. (and message limits somewhere down the line)
=> Dice extension

Binaries/bin-conf/flhook_plugins/jump.cfg, Plugins/Public/playercntl_plugin/HyperJump.cpp
Created a new form of jump denial. death_system will kill the jumpship, but leave any ships brought. banned_system will cause the device to pick a different system instead. This keeps the exploration element of jumpdrives, while removing the ability for ships to jump into systems that they cannot escape from / ooRP systems.
=> Remove the ability for ships to get stuck when blind jumping

Plugins/Public/cloak_plugin/Cloak.cpp
Should only affect charging, not already-cloaked players.
=> cloak: Remove check for jumping when player is already fully cloaked

Plugins/Public/mobiledocking_plugin/Main.cpp, Plugins/Public/mobiledocking_plugin/Main.h
Main changes:
1) Now players won't be redirected to last real base they were on if they died after being docked to carrier. This part of code suspected to be responsible for character-erasing bug.
2) Conn exploit check removed, jumps to conn were restricted long time ago, so I think it's fine.
=> Docking modules fix

Plugins/Public/mobiledocking_plugin/Main.cpp
Main changes:
1) Redirecting players to last real base is returned, because doesn't cause character-erasing bug.
2) Now when redirecting to proxy base in another system, plugin updates current system value in player list.
3) More irrelevant Connecticut checks removed. This one supposed to restrict docking in conn, but didn't work anyway. I replaced it with new one: none able to /return from conn with docked ships on board.
=> mobiledock: Fixes

Plugins/Public/autobuy/Main.cpp, Plugins/Public/autobuy/Main.h
A long time abandoned idea, got its life after new dynamic packet functionality was introduced.
Contributors:
dsyalex - Would never be able to reach this without his WIP auto-repair stuff
Notes:
1) NEVER reload it at runtime, all autobuy settings will be nullified for all player that were online.
2) Requires dynamic packet stuff from previous pull request to work.
=> autobuy: Auto-Repair

Binaries/bin-conf/flhook_plugins/alley_npc.cfg, Plugins/Public/npc_control/Main.cpp
Reverts DiscoveryGC/FLHook#98
We ran into loads of problems with this, there seems to be all sorts of hidden compatibility and memory usage issues associated with it.
=> Revert "npc_control: Advanced NPC disabling"

Plugins/Public/npc_control/Main.cpp
**Examples:**
_.aifollow_ (Will follow the admin and send a message to command giver saying "Following Player1".
_.aifollow player2_ (Will follow the 2nd player and send a message to command giver  saying "Following Player2".
If you try to use this on a character that is not online you get: "Player2 is not online".
If you try and use this on a character that is not in space you get: "Player2 is not in space"
=> npc-control: Added optional parameter to .aifollow to specify which character to follow

Binaries/bin-conf/flhook_plugins/alley_npc.cfg, Plugins/Public/npc_control/Main.cpp
Added 2 optional infocard parameters to npc in alley_npc.cfg. Either one or two infocard parameters may be used. If none are specified it will generate random names as per previous functionality.
=> npc-control: Added 2 optional infocard parameters

Plugins/Public/playercntl_plugin/HyperJump.cpp, Plugins/Public/playercntl_plugin/Main.cpp
1. Removed:
a. Commented out code.
b. Death and banned systems.
c. Detection of macro users (code to catch assholes) as it may ban users who just use Ctrl + ↑ to quickly pull coordinates from chat history.
d. .testjump command
2. Added:
a. System whitelist checks at blind jumps and /setcoords command.
b. Inability to use /setcoords while jumping.
=> HyperJump (1/7)

Plugins/Public/base_plugin/Main.cpp
Suggesting so the player logged as admin could buy stuff regardless of min_stock restrictions. I changed shop settings too much, just to buy stuff and lock it back as unbuyable.
=> Base will allow to buy stuff regardless to min_stock restriction

Plugins/Public/playercntl_plugin/Message.cpp
fix for https://discoverygc.com/forums/showthread.php?tid=182469
Deathtime now won't be posted unless '/set dietime' is enabled. (as intended)
=> 'set chattime on' now now not ignoring 'diemsg'-setting anymore

Plugins/Public/base_plugin/PlayerCommands.cpp
Players want the ability to donate to pob banks without admin access.
So if admin is not present, they can donate some money and keep the base floating with supplies it would not accept otherwise.
=> base: Allow /bank deposit and status without admin access

Plugins/Public/event/Main.cpp
This allows the ID of a TradeEvent to be used as a TargetID of a CombatEvent.
=> Allow TradeEvent to be TargetID of CombatEvents

Plugins/Public/event/Main.cpp, Plugins/Public/minecontrol_plugin/Main.cpp
Continuing issue https://github.com/DiscoveryGC/FLHook/issues/48
While using Laz's closed pull request: https://github.com/DiscoveryGC/FLHook/pull/76
While slightly editing it, so there would be no repeatable phrases too much at one time. 
(made checking for one-second difference between msgs to the same address)
Short description: Besides sound, there will be console notification about miner's cargo full for miner and target transport.
(Instead of just sound only for miner)
=> minecontrol, event: feature, miner's notifications (12.10.20)

Plugins/Public/base_plugin/Main.cpp
We discussed it before, this is what you suggested Alex.
Better description: there is bug that anyone can buy goods more than minstock allows.
By taking into account how much 'customer' requested, the amount of goods will be never lower than minstock amount.
=> base: fix for shop bug with minstock (fixed 12.10.20)

Plugins/Public/pvecontroller/Main.cpp
Bounty Payout will be multiplied depending on the difference between ship class that killed the target NPC and the ship class of the target NPC.
Important:  LowerBound is used, while the code doesn't apply a modifier of 1.0, an entry that has a 1.0 modifier is needed.
Example Config entries:
; This groups the "shipclass" used in shiparchs into categories, or types, to simplify comparison for class-diff and allow the groupings themselves to be adjusted.
; class_type = class, ship_class1, ship_class2, ship_classN (can have as many or as few
class_type = 0, 0, 1, 3, 19
class_type = 1, 2, 4, 5, 6, 7, 8, 9, 10
class_type = 2, 11, 12
class_type = 3, 13, 14
class_type = 4, 15
class_type = 5, 16, 17, 18
; Scaling settings for payouts based on class difference of player that killed NPC.
; …
=> Class Difference Multipliers

Plugins/Public/base_plugin/Main.cpp, Plugins/Public/base_plugin/Main.h, Plugins/Public/base_plugin/PlayerBase.cpp
Creating to replace https://github.com/DiscoveryGC/FLHook/pull/120 which was broken due to force pushed commits. Apperently I should re open PR before force pushing commits, if I don't want to close PR forever.
Description:
This change makes neutral or friendly aligned weapon platforms triggered to hostile state not just from any damage
but from certain sum of damage performed by one player during 24 hours
for example, 400000 (float setting damage_threshold is added for config file)
Every player has separate counter remembering how much damage they did to base (attached to their ship name)
=> base: weapon platform hostility delay.

Plugins/Public/pvecontroller/Main.cpp
Currently. there are only system-wide multipliers which globally effect bounty rewards for everyone regardless of faction.
With the added war zone spawns for NPCs, some players take advantage of this by using ships hostile to both factions in order to farm the higher spawn rates. 
This allows affiliation specific multipliers which can be used alongside system multipliers to balance / nerf / buff bounty rewards between factions involved in a warzone vs factions not involved in a warzone.
=> PvE Controller Warzones

Binaries/bin-conf/flhook_plugins/autobuy.cfg, Plugins/Public/autobuy/Main.cpp
fixing msgs to a user for a better interface
adding jumpdrive and matrix batteries into separate sections
and fixing some bug tied to it which made batteries bought twice
autobuy.cfg should be corrected in its last records. It has just  jump drive related records written there, there should be added [jump] prefix making them into separate section. +adding matrix section with record for it.
=====delete from autobuy.cfg=====
```
[extra]
item = dsy_cloak_1, missile01_mark01_ammo
item = dsy_cloak_2, missile01_mark01_ammo
item = dsy_cloak_3, missile01_mark01_ammo
item = dsy_cloak_4, missile01_mark02_ammo
item = dsy_cloak_1_n, missile01_mark04_ammo
item = dsy_cloak_2_n, missile01_mark04_ammo
item = dsy_cloak_3_n, missile01_mark04_ammo
item = dsy_nomad_cm_01, missile01_mark04_ammo
item = …
```
=> Autobuy: better user msgs, minus bug, separated jump/matrix batteries (12.10.20)

Plugins/Public/alley/PlayerRestrictions.cpp, Plugins/Public/base_plugin/Main.cpp, Plugins/Public/cloak_plugin/Cloak.cpp, Plugins/Public/npc_control/Main.cpp, Plugins/Public/playercntl_plugin/HyperJump.cpp, Plugins/Public/pvecontroller/Main.cpp, Source/FLHook/CCmds.cpp, Source/FLHook/CCmds.h, Source/FLHookPluginSDK/headers/FLHook.h
feat(set_admin): adds four new subgroups to set admin command
setadmin PlayerName chasepull, which allows
```
chase
pull
```
setadmin PlayerName aicontrol, which allows
```
aidestroy
aicancel
aifollow
aicome
aifleet
fleetlist
```
setadmin PlayerName cloak, which allows
```
cloak
```
setadmin PlayerName bases, which allows
```
testrecipe
testdeploy
basedestroy
basetogglegod
testbase
jumpcreate
basecreate
basedebugon
basedebugoff
```
Additionally:
locked commands in pvecontroller to be under
setadmin PlayerName plugins
```
pvecontroller <command>
```
and some weird commands from player_restrictions
made sure to hide(or rehide) under superadmin rights
```
showrestrictions
generateid
shiptest
healthtest1
healthtest2
testfuseobj
testunfuseobj
testselffuseobj
testselfunfuseobj
```
=> feat(set_admin): new groups, chasepull and aicontrol

Plugins/Public/playercntl_plugin/Main.cpp, Plugins/Public/playercntl_plugin/Main.h, Plugins/Public/playercntl_plugin/MiscCmds.cpp, Plugins/Public/playercntl_plugin/Rename.cpp
Descritiption: when /resetrep is used. It will nullify all reputations to zero like in fresh restart
What is it for? to restore broken reputations after changing IDs.
Restrictions for usage: 
1) It can be used only in base + it kicks (for logging to rephack your reps according to your ID)
2) It takes some credits (default price 10'000'000)
3) It can be used only once in two weeks, cooldown is resistant to renameme and movechar operations.
=> playercntl: Command /resetrep - to reset all reputations (12.10.20)

Plugins/Public/base_plugin/Main.cpp, Plugins/Public/base_plugin/Main.h, Plugins/Public/base_plugin/PlayerBase.cpp, Plugins/Public/base_plugin/PlayerCommands.cpp
- https://github.com/DiscoveryGC/FLHook/pull/158/commits/e785615c17de4bec1de6e5e4569f236054be3aa9 - hostile defense mods were locked under 'siege mod', which requires for base to receive 8 million damage for its activation. The bases will not attack everyone by default any longer, only if they were triggered to siege mode. Defense mods continue to fulfill nodock regulation role. Their role to identify hostiles is still important during activated siege mode.
- https://github.com/DiscoveryGC/FLHook/pull/158/commits/957fdd06cd00587b0264863bfb290904b32cd310 Chain reaction = activation of siege mode to one base, activates siege mods to nearby bases as well (within 8k range as the default value)
- https://github.com/DiscoveryGC/FLHook/pull/158/commits/a759c4f86ebe5a1b1a627e61942bbdef535a92e4 …
=> Base: disabling hostile defense mods

Plugins/Public/base_plugin/CoreModule.cpp, Plugins/Public/base_plugin/Main.cpp, Plugins/Public/base_plugin/Main.h
New config file properties:
Base.cfg:
damage_multiplier - float, float, float - FromHP, ToHP, Modifier - if base hp is between FromHP and ToHP (percent values from 0.0 to 1.0), multiply the wear and tear damage applied by Modifier value. Multiple entries allowed for different ranges, but only the first modifier matching a particular hitpoint percentage is ever applied. Logic defaults Modifier to 1 if no entry found.
no_crew_damage_multiplier - float - If station has insufficient crew to maintain the POB(Core level x200), the base, multiply the wear and tear by this value.
=> Added progressive Wear and Tear

Binaries/bin-conf/flhook_plugins/base_forbidden_cargo.cfg, Plugins/Public/base_plugin/Main.cpp
Requested by Haste
New functionality - forbidden commodity list on POBs. Blocks attempts to sell a given cargo on a POB regardless if it's already on the manifest, base administrator status and so on. Allows to purchase the commodity from the base if it had it onboard due to admin intervention or had it stashed before this change went live.
new .cfg file: base_forbidden_cargo.cfg
structure:
[forbidden_commodities]
commodity_name = commodity_passengers
commodity_name = commodity_cardamine
=> New functionality: POB restricted commodity list

Plugins/Public/playercntl_plugin/Main.cpp
Useful when ships have 'death fuses', and you want to prevent a 'dead' ship from docking to safety.
iCancel check is to avoid sending duplicate messages on dock attempt cancel.
=> Ships which are 'dead' cannot dock.

Plugins/Public/alley/PlayerRestrictions.cpp
While player-trade and individual item jettison is blocked by Alley's plugin Player Restriction feature, 'Jettison All' allows the player to bypass this block. This commit rectifies that.
=> Jettison All now adheres to NoTrade commodity list

Plugins/Public/alley/PlayerRestrictions.cpp, Plugins/Public/balancemagic/Main.cpp, Plugins/Public/base_plugin/Main.cpp, Plugins/Public/cloak_plugin/Cloak.cpp, Plugins/Public/pvecontroller/Main.cpp, Source/FLHook/HkCbDamage.cpp
Instead of sending our own damage entry (losing a lot of metadata such as attacker info) and stopping other plugins on the same hook from executing, we just override the new HP value that will then be 'naturally' passed on to be processed by the server and other plugins "As Chris Roberts intended"
Done by sending the 'newHealth' float as reference instead of as a copy, akin to FLHook4.
=> fix: BalanceMagic no longer stops other plugins

Plugins/Public/base_plugin/CoreModule.cpp, Plugins/Public/base_plugin/Main.cpp, Plugins/Public/base_plugin/Main.h, Plugins/Public/base_plugin/PlayerBase.cpp
Reworked the shield system to the following:
Base.cfg specifies 'vulnerability windows', time periods where bases are vulnerable. Outside of those windows, bases are straight up impervious to damage other than wear&tear. 
Shield damage reduction starts relatively low, and ramps up the reduction as station takes damage, possibly going up to 100%, rendering the station invincible before the vulnerability period ends.
The damage reduction goes back to the specified default upon entering a vulnerability window.
Config file changes:
Base.cfg:
set_shield_damage_multiplier - deprecated
base_shield_strength - float, stores the baseline damage reduction for any shielded POB. shield_reinforcement_threshold - float, damage that needs to be taken by the station to increase the damage reduction. …
=> Siege Rework

Plugins/Public/playercntl_plugin/Main.cpp
new config entry for playercntl.cfg:
DockBroadcastRange - float - decides from how far the players will see the message notifying that another player ship is attempting to dock
=> dock broadcast range unlinked from localchat range

Plugins/Public/cloak_plugin/Cloak.cpp
I couldn't personally reproduce, could be caused by FLHook/plugin config?
0x15 is another cruise disruptor damage type, and is used in other places (such as HyperJump plugin) for comparisons
=> probable fix for "CD doesn't always interrupt cloak" bug

Plugins/Public/base_plugin/CoreModule.cpp, Plugins/Public/base_plugin/Main.cpp, Plugins/Public/base_plugin/Main.h, Plugins/Public/base_plugin/PlayerBase.cpp, Plugins/Public/base_plugin/ShieldModule.cpp
- moved shield variables from CoreModule to PlayerBase
- saving relevant variables to playerbase ini file (maintain the shield parameters in case of mid-siege crash)
- removed "holiday mode fixes all POBs" code block (again)
- set the shield to online immediately on server startup, preventing a free shot before the Timer() executes for the first time
=> Siege rework enhancement

Plugins/Public/alley/PlayerRestrictions.cpp, Plugins/Public/alley/PlayerRestrictions.h, Plugins/Public/alley/shipclass_item.cpp
- added a basic check for shipclass immediately on item purchase
- said check extends to commodities as well as equipment
- old logic of checking full configuration on base launch remains unchanged
=> New: Shipclass based purchase restrictions

Plugins/Public/playercntl_plugin/Main.cpp, Source/FLHook/HkCbIClientImpl.cpp, Source/FLHookPluginSDK/headers/FLCoreRemoteClient.h, Source/FLHookPluginSDK/headers/plugin.h
stops playershot missiles from locking onto last selected target, when no target is selected.
=> Guided missile fix

Plugins/Public/base_plugin/CoreModule.cpp, Plugins/Public/base_plugin/Main.cpp, Plugins/Public/base_plugin/Main.h, Plugins/Public/base_plugin/PlayerBase.cpp, Plugins/Public/base_plugin/SaveFiles.cpp
Instead of saving all POBs once a minute, this change changes it to instead behave as a rolling update, where every second, one POB is saved until the iterator reaches the end of the list, then starts from the beginning, resulting in avoiding the massive load spike from opening and saving into ~200 files at once.
=> POB save cycle rework

Plugins/Public/playercntl_plugin/Main.cpp, Plugins/Public/playercntl_plugin/Main.h, Plugins/Public/playercntl_plugin/MiscCmds.cpp
Allows for 'cinematic' damage on Admin-flown ships during events via changing their HP and setting/unsetting fuses directly via commands
=> EventUtility: allowing admins to set HP and set/unset fuses to players

Plugins/Public/playercntl_plugin/Main.cpp
When you jump into a system, you always see tradelanes as alive, even if they were disabled by an evil pirate a moment earlier. Without the fix, you could dock and escape with pirate having no counterplay or ability to chase.
Also adds a configurable list of ships banned from using trade lanes. Ships banned from using trade lanes also cannot form onto other ships, but can be formed onto. This was done to prevent 'formation trade lane' behavior from used as a bypass for the block.
=> TradeLane: Fix TL state desync bug when crossing systems. Add Trade Lane ban list for ship archs.

Plugins/Public/alley/PlayerRestrictions.cpp
Define a percentage of cargo that will be successfully jettisoned, rest will be lost. Default behavior for undefined percentage or a defined zero will be a standard jettison block.
Also made pulling names for error messages dynamic instead of relying on config.
=> Jettison: Adjusting Alley notrade to allow partial jettison

Plugins/Public/cloak_plugin/Cloak.cpp, Source/FLHook/HkCbIClientImpl.cpp, Source/FLHookPluginSDK/headers/FLCoreRemoteClient.h, Source/FLHookPluginSDK/headers/plugin.h
By default it replaces the cloak alert sound with cloak entry sound, to restore that, put the following into cloak.cfg
[General]
cloak_alert_sound = dsy_jumpdrive_survey
=> Cloak momentum based consumption

Plugins/Public/alley/PlayerRestrictions.cpp, Plugins/Public/alley/dockrestrict.cpp, Plugins/Public/base_plugin/Main.cpp, Plugins/Public/cloak_plugin/Cloak.cpp, Plugins/Public/mobiledocking_plugin/Main.cpp, Plugins/Public/playercntl_plugin/Main.cpp, Source/FLHook/HkCbIEngine.cpp
IMPORTANT: REQUIRES DOCK_CALL METHOD ADJUSTMENTS ON PRIVATE PLUGINS!
Sadly we're unable to cleanly override RequestEvent hook at the moment, as such this will not have effect on neutral-no-dock restriction.
=> Docking: More organic Dock_Call overrides

Plugins/Public/mobiledocking_plugin/Main.cpp, Plugins/Public/playercntl_plugin/Main.cpp, Plugins/Public/playercntl_plugin/Main.h, Plugins/Public/playercntl_plugin/SystemSensor.cpp, Source/FLHook/HkCbIEngine.cpp, Source/FLHook/HkCbIServerImpl.cpp, Source/FLHook/Hook.h
Fixes the issue where without explicitly doing a Server.RequestCancel() on a docking request that was changed by a plugin from success to failure, causes the server to periodically (once every 90 seconds) to re-attempt the dock.
Also fixes the issue where ACCESS_DENIED status did not play an appropriate voiceline on its own.
=> Dock_Call bugfixes

Plugins/Public/JSONBuddy/Main.cpp, Plugins/Public/JSONBuddy/condata.cpp
Current /pingtarget is not informative enough without any latency info.
With very loose thresholds it gives a general idea about the connection without risking exposing the player by noting a specific ping value.
=> PingTarget: Now provides very aproximate ping

Plugins/Public/base_plugin/CoreModule.cpp, Plugins/Public/base_plugin/Main.cpp, Plugins/Public/base_plugin/Main.h
As long as base is shielded, only specific siege weapons are capable of dealing damage (during vulnerability window), unless no siege guns are defined.
Attacking with non-siege gun will still trigger a shield, however.
=> Siege weaponry dmg override

Plugins/Public/cloak_plugin/Cloak.cpp, Source/FLHookPluginSDK/headers/plugin.h
One-commit version of #233
List of changes:
Cloak fuel consumption scales with speed using a quadratic formula,.making standing still consume little fuel, and moving causing progressively larger consumption.
Cloaks now get disrupted via proximity to nongrouped player ship.
Cloaks still produce sound when within disruption range of a grouped ship
Cloak distance check moved clientside and massively increased in frequency for improved responsiveness and server performance
=> Cloak rework: fuel, detection, clientside checks

Plugins/Public/playercntl_plugin/Main.cpp
CLoot containers are effectively unmovable objects, causing any ship that tries to fly into one to either quickly bounce off in case of smaller ships, or spin violently in case of caps. This destroys the CLoot containers when collided at above-trivial speed (default 25, configurable)
=> Destroy CLoot on collision

Plugins/Public/autobuy/Main.cpp, Source/FLHook/HkCbIClientImpl.cpp, Source/FLHookPluginSDK/headers/plugin.h
When buying a capital ship, game doesn't validate the bot/batt count on the new ship, letting people end up with a ship holding nanobots where none should be present. (one time only, but still)
This hook triggers only on new ship purchase, and upon detecting an excess of either bots or batts, removes the excess and reimburses the player the appropriate amount.
=> Add max bot/batt check on ship purchase, sell the excess.

Plugins/Public/playercntl_plugin/Main.cpp
SystemSwitchOutComplete turns out to actually be a packet-type hook, it sends info about a ship dissapearing into a jump tunnel to every player in range. As such, blindly assuming it is the iClientID that jumped out is false most of the time.
=> MobileDock: Fix system jump out detection.

Plugins/Public/playercntl_plugin/Main.cpp
Fixes bug introduced in #220
Nomad Trade Lanes are not disruptable and have no shields, hence the check would always fails the dock attempt when it should always succeed.
=> Tradelane: Fix the shield check nomad TradeLanes (they have no shield)

Plugins/Public/cloak_plugin/Cloak.cpp
Done to prevent being able to activate cloak, then deactivate it to achieve a permanent transparency on your ship. The deactivation fails if done by a command, and in case of running out of fuel, is delayed until the sequence finishes.
Also, minor code optimization.
=> Cloak: Prevent disabling of cloak during activation sequence. Fix sub-zero fuel consumption logic.

Plugins/Public/base_plugin/Main.cpp, Plugins/Public/conn_plugin/Main.cpp, Plugins/Public/mobiledocking_plugin/Main.cpp, Plugins/Public/playercntl_plugin/Rename.cpp, Source/FLHookPluginSDK/headers/plugin.h
-Renaming a character fires a cross plugin event that force lands it to last docked solar/POB.
-Unable to go to /conn while mobile docked. (being actually docked on a POB but actually mobiledocked but ACTUALLY on New Haven is just a bit much)
-Server crash fixes fixes related to incorrect clearing of the containers and miscounting a counter.
=> MobileDocking: Bugfixes and adjustments

Plugins/Public/base_plugin/Main.cpp, Plugins/Public/base_plugin/Main.h, Plugins/Public/base_plugin/PlayerBase.cpp, Plugins/Public/base_plugin/PlayerCommands.cpp
-Allows admins to define fields containing select 'low tier' commodities to be exempt from the distance checking, for example water, oxygen, toxic waste.
-Adjusts printing for the 'checkBaseDistances' utility
-Contains a compile fix - removal of nonexistent repairing field from PlayerBase constructor
=> Mining allow deployment for low tier mining

Plugins/Public/pvecontroller/Main.cpp
-Allows to specify the loot amount to drop.
-Allows to specify multiple entries per ship class. (clearly was originally the plan as the container is a multimap, but only the first value is read)
-Code cleanup.
=> PVE controller: customizable drop quantities, multiple entries supported.

Plugins/Public/base_plugin/Main.h, Plugins/Public/base_plugin/PlayerBase.cpp
Results in no wasted CPU cycles, and no shields being triggered. win-win.
=> POBs: Indestructible POBs don't process damage taken.

Plugins/Public/alley/shipclass_item.cpp
In the past, the CUSTOM_BASE_LAST_DOCKED and CUSTOM_BASE_IS_DOCKED cross plugin callouts were duplicates and did exactly the same thing. I repurposed CUSTOM_BASE_LAST_DOCKED to instead return a name for purposes of a different plugin, but forgot to point Alley's code to the other remaining call.
=> Alley: CrossPlugin call adjustment

Plugins/Public/base_plugin/BuildModule.cpp, Plugins/Public/base_plugin/CoreModule.cpp, Plugins/Public/base_plugin/FactoryModule.cpp, Plugins/Public/base_plugin/Main.cpp, Plugins/Public/base_plugin/Main.h, Plugins/Public/base_plugin/PlayerCommands.cpp
-incorrect handling of factory building
-unintuitive configs for refinery modules
-craft lists not being cleared on module destruction -craft lists not being selectable via numbers
-various optimizations, including food consumption and FactoryModule saving.
=> (MustHave)POBCraft: Fix issues with refineries

Plugins/Public/mobiledocking_plugin/Main.cpp, Plugins/Public/mobiledocking_plugin/Main.h
Stops people from teleporting snubs across the sector instantly via going for example, Omega-3 -> Conn -> New Tokyo instantly.
=> (AlmostMustHave)MobileDock: Stop mobile docking from working in certain systems(conn)

Plugins/PluginUtilities/PluginUtilities.cpp, Plugins/PluginUtilities/PluginUtilities.h, Plugins/Public/base_plugin/Main.cpp, Plugins/Public/playercntl_plugin/Main.cpp, Source/FLHookPluginSDK/headers/plugin.h
In some circumstances, the player position was already set to 0,0,0. As such, we use the Base position itself.
=> Change player dock broadcast from around the ship to around the base

Plugins/Public/event/Main.cpp, Plugins/Public/kill_tracker/Main.cpp, Plugins/Public/playercntl_plugin/Main.cpp, Source/FLHook/HkCbDeath.cpp
Kill_Tracker now overrides the killer ID with the top damage contributor, allowing Event plugin to use it.
Event plugin now uses INT32_MAX as default value for objectiveMax variables.
=> Event: Minor rework

Plugins/Public/kill_tracker/Main.cpp
SItuation in which an incorrect g_LastHitPts is being passed down remains unknown.
=> Kill_Tracker bandaid fix

Plugins/Public/conn_plugin/Main.cpp
Transfer Flag is already cleared on line 380.
Clearing of the data should only even occur on character select/clearclientinfo
=> Conn: Remove unnecessary data purging

Source/FLHook/HkCbIClientImpl.cpp
Replace WriteProcMem() with a simple memcpy()
=> Epic optimization in HkIClientImpl::CDPClientProxy__GetLinkSaturation

Plugins/Public/base_plugin/PlayerCommands.cpp
Prevent dereference of a nullptr aka empty module in /base defmod method. Replaced with a dynamic_cast.
=> Exception fix in /base Defmod command

Source/FLHook/HkCbIServerImpl.cpp
Replace not-immediately-obvious comparisons of numeric values with themselves with explicit isnan() calls. Also added the missing rotation's W variable from the comparison. Also tightened the threshold for what we consider a valid rotation Quaternion. It's still ~50% looser than what should be theoretically possible.
=> SpObjectUpdate NAN check update

Plugins/Public/base_plugin/FactoryModule.cpp, Plugins/Public/base_plugin/Main.h, Plugins/Public/base_plugin/PlayerCommands.cpp
Currently POBs have no command to clear pending queues of factories without stopping currently ongong recipes as well. This is a fast fix until I come up with a command targeting a specific factory.
=> ClearQueue command for POBs added

Plugins/Public/playercntl_plugin/HyperJump.cpp
Fix issues with Jump Drives incorrectly telling the player that they are out of jump range when blind jumping into Earhart, when they reach 100% charge.
=> JumpDrives: Enhanced Jump hole tunnel handling

Plugins/Public/base_plugin/Main.cpp, Plugins/Public/mobiledocking_plugin/Main.cpp
Removed completely unnecessary code that was causing players to be beamed to last docked POB if logging into space to a system different from said POB. It also interfered with mobile docking due to players ending up in Limbo system as opposed to where they were originally 'picked up' by their carrier.
Also a few minor optimizations in related code.
=> Fix docking on POBs when mobile docked

Plugins/Public/mobiledocking_plugin/Main.cpp, Plugins/Public/playercntl_plugin/Main.cpp
PlayerCntl: move the message print to a separate check where dockPort == -1
MobileDock: move the returncode override to after it's confirmed the target is a player.
=> Fix dock message bug for good.
