DiscoveryGC/FLHook

trunk/source/HkFuncLog.cpp

Avoid crashing if we can't write logs

---

trunk/plugins/alley/PlayerRestrictions.cpp
trunk/plugins/alley/dockrestrict.cpp

alley plugin: Avoid crashing if we can't write logs

---

Plugins/Public/playercntl_plugin/Message.cpp

So they don't look like group messages.

Change colour of faction messages

---

Binaries/bin-conf/flhook_plugins/playercntl.cfg
Plugins/Public/playercntl_plugin/Main.cpp
Plugins/Public/playercntl_plugin/Main.h
Plugins/Public/playercntl_plugin/Message.cpp

To reduce the current wall of text that is /help, per Spazzy and Crazyr0m
(who came up with basically the same idea independently).

Command list command

---

Plugins/Public/playercntl_plugin/Main.cpp
Plugins/Public/playercntl_plugin/Player Control Plugin.vc14.vcxproj
Plugins/Public/playercntl_plugin/Rename.cpp

* Lock HpCM* (Cloaks, Cloak Disruptors) as well as cargo
* Allow for an extra lock level that restricts selling anything.
http://discoverygc.com/forums/showthread.php?tid=146200

playercntl: Allow further locking of ships

---

LegacyContent/dsace_client_hook/public_funcs.cpp
Plugins/Public/alley/PlayerRestrictions.cpp
Plugins/Public/minecontrol_plugin/Main.cpp

Reuses UserCmd_Process code from another plugin
Reuses a bunch of code from playercntl to do the actual dropping.
In minecontrol because I felt that's where it's really useful. We can move
it elsewhere if wanted.
http://discoverygc.com/forums/showthread.php?tid=146352

Add /jettisonall command to jettison all cargo

---

FLHook.sln
Plugins/Public/getrep/Main.cpp
Plugins/Public/getrep/Main.h
Plugins/Public/getrep/Rep.vcxproj
Plugins/Public/getrep/Rep.vcxproj.filters

New Command: /rep - This command will display the full list of npc reputations for the player. It will list them in order of reputation, rather than faction name.

Getrep Plugin

---

Plugins/Public/playercntl_plugin/Main.cpp
Plugins/Public/playercntl_plugin/Main.h
Plugins/Public/playercntl_plugin/Message.cpp

A toggle which timestamps death messages.

/set dietime [on|off] command

---

Plugins/Public/autobuy/Main.cpp

This commit re-adds stackable ammo counts for missiles and guns to the autobuy plugin. The list of weapons that are stackable is configured in `autobuy.cfg`, with the following format:
```
[stackable]
weapon = torpedo03_mark01
weapon = dsy_silencer_missile
weapon = dsy_nightmare_torpedo
```
Any gun, missile launcher, or torpedo launcher given a `weapon = <id>` entry under the `[stackable]` section in `autobuy.cfg` will be considered stackable, ie. having multiple of the same launcher equipped will increase the amount of ammo the autobuy plugin loads into your ship accordingly. For example, equipping two Hellfire Rocket Pods will result in twice the ammo capacity of a single rocket pod (120 each) being loaded into your ship by the autobuy plugin.

Re-add stackables to autobuy plugin

---

Plugins/Public/balancemagic/Main.cpp

Includes splitting of fighter balance as per Durandal's request, and some mostly working but dummied-out-via-configuration burstfire code. I need to spend some time working on that one a bit more (the fighter balance split works fine though).

balancemagic: rollup of changes requested by balance team

---

Plugins/Public/mobiledocking_plugin/Main.cpp

Changes:
1) Added admin command .logactivity which creates log file with list of all clients found in docking modules plugin data and at server at all.
2) Client info is being cleared from plugin after disconnect. Made for giving most relevant results with .logactivity command. DisConnect functionality is moved to separate function.
3) Few command now return true instead of false. Not supposed to hurt, but better to be sure.

mobiledock: Minor fixes and debug functionality.

---

Plugins/Public/mobiledocking_plugin/Main.cpp

Update system stat in player list for redirecting to carrier's base.

mobiledock: The thing I forgot to put in

---

Plugins/Public/hookext_plugin/hookext_exports.h

Exports two more functions correctly.

HookExt exports fix

---

Binaries/bin-conf/flhook_plugins/pvecontroller.cfg
FLHook.sln
Plugins/Public/pvecontroller/Main.cpp
Plugins/Public/pvecontroller/Main.h
Plugins/Public/pvecontroller/pvecontroller.vcxproj

Take three at actually getting my branches to not break horribly...
This PR is for the initial plugin work for the PvE controller. It is feature complete up to the bits required for the Rheinland Update (and as of this commit, for using system bonus multipliers for ie. events). This plugin is new but has been fairly extensively tested on the development test server in many different scenarios and group sizes.

pvecontroller: Add PvE Overhaul Phase 1 code.

---

Plugins/Public/pvecontroller/Main.cpp

* Prevent AddDmgEntry kill logic from running on entities other than ships; should fix exceptions in AddDmgEntry.
* Prevent Disconnect and CharacterInfoReq jams that cause the server to fill up with phantom players by doing NPCBountyPayout() on BaseEnter for now instead of in Disconnect and CharacterInfoReq.
ClearClientInfo covers what we really need it to as far as disconnecting goes, plus the implicit call to it in FLHook's own OnConnect.

pvecontroller: Fixes for issues seen in day one live deployment

---

Plugins/Public/playercntl_plugin/HyperJump.cpp

You can /survey while being bumped by NPC within 400 distance by x, y, z (not 5 as before)

Hyper scanner fix

---

Plugins/Public/base_plugin/Main.h
Plugins/Public/base_plugin/PlayerCommands.cpp

base: Prevent login brute force (12.10.20)

---

Plugins/Public/base_plugin/FactoryModule.cpp
Plugins/Public/base_plugin/Main.h
Plugins/Public/base_plugin/PlayerCommands.cpp

a player command to clear active recipe from factory module

base: Allow clearing queue(active recipe) fully for factory module (upd 12.10.20)

---

Plugins/Public/base_plugin/CoreModule.cpp
Plugins/Public/base_plugin/DefenseModule.cpp
Plugins/Public/base_plugin/Main.h
Plugins/Public/base_plugin/PlayerBase.cpp

fix(base): fix to weapon platform changes hostility delay in https://github.com/DiscoveryGC/FLHook/pull/144

fix(base): fix to weapon platform changes hostility delay

---

Plugins/Public/base_plugin/BuildModule.cpp
Plugins/Public/base_plugin/FactoryModule.cpp
Plugins/Public/base_plugin/Main.h
Plugins/Public/base_plugin/PlayerCommands.cpp

pause and resume ability for module and device construction
new commands
/base facmod switch <Index>//pauses if active, resumes if paused
/base buildmod switch <index> //pauses if active, resumes if paused

base: Allow pausing and resuming facmod and buildmod (12.10.20)

---

Plugins/Public/base_plugin/Main.cpp
Plugins/Public/base_plugin/Main.h
Plugins/Public/base_plugin/PlayerBase.cpp
Plugins/Public/base_plugin/PlayerCommands.cpp

feat(baseplugin): adding new docking permissions based on IFF.
adding new commands /base addfac, /base rmfac, /base lstfac, /base myfac
they make possible to add as friendly or hostile a whole faction by their IFF
this changes their docking permissions and friendly/hostile attitude to base

base: Allow faction-based docking rights (12.10.20)

---

.gitignore

They keep bothering me.
Lets ignore them, in worst case we can add them to commit through -f option anyway, if there will be ever need for it

refactor(gitignore): adding to ignore unnecessary headers/libs

---

Plugins/Public/base_plugin/ExportData.cpp

Exporting shield state from base plugin to JSON
in order to be able notifying about base attacks

feat(base): JSONifying shieldstate

---

Plugins/PluginUtilities/PluginUtilities.cpp
Plugins/Public/autobuy/Main.cpp
Source/FLHook/FLHook.cpp
Source/FLHook/HkCbIClientImpl.cpp
Source/FLHookPluginSDK/headers/FLCoreRemoteClient.h
Source/FLHookPluginSDK/headers/FLCoreServer.h
Source/FLHookPluginSDK/headers/st6.h

Disclaimer: Other plugins depending on DynPackets will most likely still require the Win7 compatibility mode to work properly, unless we'd apply the ST6 solution to them as well.

Autobuy now repairs component, doesn't require FLServer running in legacy compatibility mode

---

Plugins/Public/base_plugin/Main.cpp
Plugins/Public/base_plugin/Main.h
Plugins/Public/cloak_plugin/Cloak.cpp
Plugins/Public/pvecontroller/Main.cpp

Correcting signature for HkCb_AddDmgEntry to be in line with Core.
Rehooking PVEController to use ShipDestroyed instead, for notable performance improvement.

Add dmg entry optimizations

---

Plugins/Public/alley/PlayerRestrictions.cpp

Note: healingrates.cfg will move from data/equipment to exe/flhook_plugins folder

Optimizing Repair-ship code. Adding max healing limitation.

---

Plugins/Public/base_plugin/Base Plugin.vc14.vcxproj
Plugins/Public/base_plugin/EquipmentUtilities.cpp
Plugins/Public/base_plugin/ExportData.cpp
Plugins/Public/base_plugin/Main.cpp
Plugins/Public/base_plugin/Main.h
Plugins/Public/base_plugin/PlayerBase.cpp
Plugins/Public/base_plugin/PlayerCommands.cpp
Plugins/Public/playercntl_plugin/Main.cpp
Plugins/Public/playercntl_plugin/Main.h
Plugins/Public/playercntl_plugin/Player Control Plugin.vc14.vcxproj

outputting base items to JSON with key `shop`
which players are wishing to show
by default all items are private
with 
`/shop public #NumberInShop`, item can become public
`/shop private #NumberInShop`, in order to hide item back
Also added for output `money`
which is needed in order to decide if the base is capable to buy things it made public

feat(base): outputing chosen base items to JSON

---

Plugins/Public/base_plugin/Main.cpp
Plugins/Public/base_plugin/Main.h
Plugins/Public/base_plugin/PlayerCommands.cpp

Made it so spamming a bunch of POBs is deterred by massive upfront credit cost.

BaseDeploy: Add configurable credit cost

---

Plugins/Public/playercntl_plugin/Main.cpp
Source/FLHook/HkCbIClientImpl.cpp
Source/FLHookPluginSDK/headers/plugin.h

Prevents people spamming F3-ESC-F3-ESC to generate dozens of green text docking messages.

Dock message on dock not f3

---

Plugins/Public/base_plugin/PlayerCommands.cpp

-`/shop price` got split into `/shop price` and `/shop stock`
-Admin logins and shop events are now logged to file.

Pob shop and logging enhancements

---

Plugins/Public/minecontrol_plugin/Main.cpp

Fetched wrong value, ended up going out of bounds for the array.

MiningPlugin: Fetch ship class instead of type

---

Plugins/Public/mobiledocking_plugin/Main.cpp

Not adding to spreadsheet, bonus/postpatch territory

MobileDock: now broadcasts the dock attempt.

---

Plugins/Public/cloak_plugin/Cloak.cpp

Cloaks are now restricted by ship type instead of cargo hold capacity.

Cloak shiptype restriction

---

Plugins/Public/autobuy/Main.cpp
Source/FLHook/HkCbIClientImpl.cpp
Source/FLHookPluginSDK/headers/FLCoreCommon.h
Source/FLHookPluginSDK/headers/FLCoreRemoteClient.h
Source/FLHookPluginSDK/headers/FLCoreServer.h

- Now pulls the hull and equipment repair factors directly from common.dll and server.dll respectively
- Now calculates costs for collision group repair
- Minor code cleanup

Autobuy repair enhancements

---

Plugins/Public/commoditylimit/Main.cpp

Value of stock == 500 is used globally for every base selling a given commodity.

BuyBackBlock: Simply block all bases selling a defined good from buying it.

---

Plugins/Public/base_plugin/Main.cpp

Base: Fix non-superadmins not being able to beam to POBs.

---

Source/FLHook/CCmds.cpp
Source/FLHook/CCmds.h
Source/FLHook/FLHook.cpp
Source/FLHook/HkCbIEngine.cpp
Source/FLHook/HkCbIServerImpl.cpp
Source/FLHook/HkTimers.cpp
Source/FLHook/Hook.h
Source/FLHook/Settings.cpp
Source/FLHook/global.h

Allows for real time sampling of performance timers on both global scale and on individual hook scale

Enhanced performance logging

---

Plugins/Public/base_plugin/BuildModule.cpp
Plugins/Public/base_plugin/CoreModule.cpp
Plugins/Public/base_plugin/ExportData.cpp
Plugins/Public/base_plugin/FactoryModule.cpp
Plugins/Public/base_plugin/Jumper.cpp
Plugins/Public/base_plugin/Main.cpp
Plugins/Public/base_plugin/Main.h
Plugins/Public/base_plugin/PlayerBase.cpp
Plugins/Public/base_plugin/PlayerCommands.cpp

-Credit consumption increased to 100x the consumption rate, up from 10x -Factory logic loop optimizations and fixes
-Core upgrade module built in a separate build slot -Build material consumption logic fix
-HP refresh moved from a timer to SetTarget hook for optimization purposes -Disabling JSON commodity exporting, optimization of the process. -Factory module more vocal about various status changes. -HyperjumpHub: logging out in uncharted system instakills the player. -Dangling freed pointers now cleared, crashfixes.

Various small POB changes

---

Plugins/Public/conn_plugin/Main.cpp

Only write to player file on entering conn
Only read from player file if they log into Connecticut system Otherwise use cached data.

Conn: File operations optimizations.

---

Plugins/Public/mobiledocking_plugin/Main.cpp
Plugins/Public/mobiledocking_plugin/MobileDocking Plugin.vc14.vcxproj

Also removal of unnecessary plugin dependency

MobileDock: Fixes, configurable cargo allowance.

---

Plugins/Public/alley/shipclass_item.cpp

See title
format is `exempt = <ship internal nickname>`

Allow defining exceptions to shipclass_item ID restrictions

---

Source/FLHook/Hook.h

Also removed old timer methods that aren't useful.

Hook timer logging now toggleable via #define in hook.h

---

Plugins/Public/mobiledocking_plugin/Main.cpp

Per request in https://discoverygc.com/forums/showthread.php?tid=200399

mobiledocking: Add aliases for player commands
